### ISSUE TITLE
Zelf Wallet - Android Offline Create Random Zelf Name

### ISSUE THREAD

**Issue by carlosbleck** [Open-Verifik/zelf-android-online#1]
## Description
Make Zelf Offline Version totally usable without Internet Connection for Onboarding Flow (Create and Import Wallet)

### Todo
- [x] New flow on Android Offline version when creating or importing a new wallet.
- [x] A new random name with the form of zoff····· is created avoid duplicates on IPFS system.
- [x] Return Onboarding screens to the old design.

**Comment by johsecaba** [comment]
QA succesful!
