### ISSUE TITLE
Update assets and NFT view to new UI

### ISSUE THREAD

**Issue by carlosbleck** [Open-Verifik/zelf-android-online#11]
# Description
Change the assets and NFT view to new UI

## TODO:

- [x] Change assets to new UI
- [x] Change NFT to new UI
- [x] Add functionality to assets and NFT view

<img width="235" alt="Image" src="https://github.com/user-attachments/assets/65a4aac3-f6dd-4ada-a409-1802a4a09241" />
