### ISSUE TITLE
Scan QR to send assets flow

### ISSUE THREAD

**Issue by carlosbleck** [Open-Verifik/zelf-android-online#16]
# Description

Connect all the process for scanning a QR

## TODO

- [ ] Change QR UI
- [ ] Make all the requests needed to work and screen connections
- [ ] Test the flow
